### ISSUE TITLE
docker compose fails on macs for port 5000

### ISSUE THREAD

**Issue by zsaltys** [awslabs/aws-dataall#263] opened 2022-12-21 10:29 UTC
### Describe the bug

docker-compose up fails with Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use

due to:

https://medium.com/pythonistas/port-5000-already-in-use-macos-monterey-issue-d86b02edd36c

### How to Reproduce

run docker-compose up on a mac

### OS

Mac

### Python version

N/A

### AWS data.all version

N/A

**Comment by zsaltys** [comment] 2022-12-21 10:39
workaround: https://developer.apple.com/forums/thread/682332

**Comment by dlpzx** [comment] 2022-12-22 11:53
Yes, I ran into the same issue a while ago. I will close it as it is not a bug of data.all but a generic issue.

**Closed by dlpzx** 2022-12-22 11:53 UTC
Labels: bug

**Comment by zsaltys** [comment] 2023-01-05 12:38
@dlpzx would it be worth using a different port than 5000 to avoid people rediscovering this issue?
