### ISSUE TITLE
cdk synth execution error

### ISSUE THREAD

**Issue by anilprobable** [awslabs/aws-dataall#495] opened 2023-06-02 07:34 UTC
*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*
Hi, 

We are implementing data.all environment in Prod account and while executing "cdk synth" getting following error, from Windows 10 using git bash.  

Could anyone please provide immediate fix . We have already implemented data.all in Dev and QA (1 month back) environment without any issue, but getting issue in prod deployment.

[2023-06-01 13:35:17,932][credentials.py:1180] Found credentials in environment variables.
[2023-06-01 13:35:19,640][app.py       : 40] Trying to get cdkjson parameter from SSM
[2023-06-01 13:35:20,806][app.py       : 49] SSM parameter not found - Proceeding with cdk.json and cdk.context.json in code
[2023-06-01 13:35:20,820][app.py       : 54] Loaded context from cdk.json file in repository
Bundling asset dataall-prddeploy-cicd-stack/dataall-prd-backend-stage/backend-stack/Cognito/OktaCognitoSyncHandlerprd/Code/Stage...
jsii.errors.JavaScriptError:
  Error: Failed to bundle asset dataall-prddeploy-cicd-stack/dataall-prd-backend-stage/backend-stack/Cognito/OktaCognitoSyncHandlerprd/Code/Stage, bundle output is located at C:\Users\rxt8103\IdeaProjects\iffdata-governance\cdk.out\asset.c4164ea80e0a799b941da720973c40aae7222fde0557434665f64b83047cafd7-error: @jsii/kernel.RuntimeError: Command '['cp -a C:\\Users\\rxt8103\\IdeaProjects\\iffdata-governance\\deploy\\custom_resources\\okta_congito_sync/. C:\\Users\\rxt8103\\IdeaProjects\\iffdata-governance\\cdk.out\\asset.c4164ea80e0a799b941da720973c40aae7222fde0557434665f64b83047cafd7/ && pip install -r C:\\Users\\rxt8103\\IdeaProjects\\iffdata-governance\\deploy\\custom_resources\\okta_congito_sync\\requirements.txt -t C:\\Users\\rxt8103\\IdeaProjects\\iffdata-governance\\cdk.out\\asset.c4164ea80e0a799b941da720973c40aae7222fde0557434665f64b83047cafd7']' returned non-zero exit status 1.
      at AssetStaging.bundle (C:\Users\rxt8103\AppData\Local\Temp\jsii-kernel-RCnM31\node_modules\aws-cdk-lib\core\lib\asset-staging.js:2:672)
      at AssetStaging.stageByBundling (C:\Users\rxt8103\AppData\Local\Temp\jsii-kernel-RCnM31\node_modules\aws-cdk-lib\core\lib\asset-staging.js:1:4168)
      at stageThisAsset (C:\Users\rxt8103\AppData\Local\Temp\jsii-kernel-RCnM31\node_modules\aws-cdk-lib\core\lib\asset-staging.js:1:1675)
      at Cache.obtain (C:\Users\rxt8103\AppData\Local\Temp\jsii-kernel-RCnM31\node_modules\aws-cdk-lib\core\lib\private\cache.js:1:242)
      at new AssetStaging (C:\Users\rxt8103\AppData\Local\Temp\jsii-kernel-RCnM31\node_modules\aws-cdk-lib\core\lib\asset-staging.js:1:2070)
      at new Asset (C:\Users\rxt8103\AppData\Local\Temp\jsii-kernel-RCnM31\node_modules\aws-cdk-lib\aws-s3-assets\lib\asset.js:1:620)
      at AssetCode.bind (C:\Users\rxt8103\AppData\Local\Temp\jsii-kernel-RCnM31\node_modules\aws-cdk-lib\aws-lambda\lib\code.js:1:3506)
      at new Function (C:\Users\rxt8103\AppData\Local\Temp\jsii-kernel-RCnM31\node_modules\aws-cdk-lib\aws-lambda\lib\function.js:1:2424)
      at Kernel._create (C:\Users\rxt8103\AppData\Local\Temp\tmp0aczn0lb\lib\program.js:9964:29)
      at Kernel.create (C:\Users\rxt8103\AppData\Local\Temp\tmp0aczn0lb\lib\program.js:9693:29)

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\deploy\app.py", line 68, in <module>
    pipeline = PipelineStack(
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\venv\lib\site-packages\jsii\_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\deploy\stacks\pipeline.py", line 257, in __init__
    backend_stage = self.set_backend_stage(target_env, repository_name)
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\deploy\stacks\pipeline.py", line 566, in set_backend_stage
    BackendStage(
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\venv\lib\site-packages\jsii\_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\deploy\stacks\backend_stage.py", line 34, in __init__
    backend_stack = BackendStack(
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\venv\lib\site-packages\jsii\_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\deploy\stacks\backend_stack.py", line 91, in __init__
    cognito_stack = IdpStack(
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\venv\lib\site-packages\jsii\_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\deploy\stacks\cognito.py", line 349, in __init__
    okta_cognito_sync_handler = _lambda.Function(
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\venv\lib\site-packages\jsii\_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\venv\lib\site-packages\aws_cdk\aws_lambda\__init__.py", line 18583, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\venv\lib\site-packages\jsii\_kernel\__init__.py", line 346, in create
    obj.__jsii_ref__ = _callback_till_result(self, response, CreateResponse)
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\venv\lib\site-packages\jsii\_kernel\__init__.py", line 263, in _callback_till_result
    response = kernel.sync_complete(
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\venv\lib\site-packages\jsii\_kernel\__init__.py", line 445, in sync_complete
    return self.provider.sync_complete(
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\venv\lib\site-packages\jsii\_kernel\providers\process.py", line 401, in sync_complete
    resp = self._process.send(_CompleteRequest(complete=request), response_type)
  File "C:\Users\rxt8103\IdeaProjects\iffdata-governance\venv\lib\site-packages\jsii\_kernel\providers\process.py", line 340, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: Failed to bundle asset dataall-prddeploy-cicd-stack/dataall-prd-backend-stage/backend-stack/Cognito/OktaCognitoSyncHandlerprd/Code/Stage, bundle output is located at C:\Users\rxt8103\IdeaProjects\iffdata-governance\cdk.out\asset.c4164ea80e0a799b941da720973c40aae7222fde0557434665f64b83047cafd7-error: @jsii/kernel.RuntimeError: Command '['cp -a C:\\Users\\rxt8103\\IdeaProjects\\iffdata-governance\\deploy\\custom_resources\\okta_congito_sync/. C:\\Users\\rxt8103\\IdeaProjects\\iffdata-governance\\cdk.out\\asset.c4164ea80e0a799b941da720973c40aae7222fde0557434665f64b83047cafd7/ && pip install -r C:\\Users\\rxt8103\\IdeaProjects\\iffdata-governance\\deploy\\custom_resources\\okta_congito_sync\\requirements.txt -t C:\\Users\\rxt8103\\IdeaProjects\\iffdata-governance\\cdk.out\\asset.c4164ea80e0a799b941da720973c40aae7222fde0557434665f64b83047cafd7']' returned non-zero exit status 1.

Subprocess exited with error 1

**Comment by anmolsgandhi** [comment] 2023-10-11 18:53
Since the question has been answered and there has been no further communication, we are closing this issue. As noted above by @dlpzx we will not be able to reproduce or look into the code that doesn't belong to the project. Please feel free to reopen the issues if you have any more questions or required further assistance.

**Closed by anmolsgandhi** 2023-10-11 18:53 UTC
Labels: status: can't reproduce, status: closing-soon, status: needs more info
