### ISSUE TITLE
Simplified workflow for sharing

### ISSUE THREAD

**Issue by manjulaK** [awslabs/aws-dataall#711] opened 2023-08-28 10:59 UTC
When we setup a share and have to go to SHARES to submit a share again.. This is not a good workflow because it requires tribal knowledge that you need to do so. For many customers there may be a need to simplify this workflow or have clear information and or prompting to help user through the workflow of re-submitting draft share . May be there can be customization parameter in cdk.json or somewhere like that that deploys a simplified workflow without draft state for customers who don't actually need it.

**Comment by dlpzx** [comment] 2023-09-05 13:11
Hi @manjulaK, I agree on the issue but the solution proposed has some remarks:

If I understand the issue, the problem is that the workflow is not intuitive for users and they might not complete the submission of a request. I totally agree with the problem. There are some alternatives to remediate this problem:

1) redirect users to the share request once it is opened so that they do not have to go to shares > search for their share > add items > submit
2) remove the draft state and directly submit requests --> technically this one presents difficulties as in the original implementation we group tables and then request them in the same batch. If each table triggers a sharing task we need to redesign the sharing to be able to handle this.

So I am more inclined towards changes in the frontend routing to improve the user experience.

**Comment by zsaltys** [comment] 2023-09-12 11:05
@dlpzx I think that a redirect for now may be sufficient.

Another option which might make sense is to get rid of the small request UI completely and improve the main share UI where a user can select everything he wants access to. Also we should probably make some UI improvements to show that the share is currently in DRAFT mode to make it very clear that it has to be submitted first.

**Comment by mvidhu** [comment] 2023-09-18 15:00
We have the same feedback in our organization. Simple redirect solution in the point 1 is also an improvement in the user journey.

**Comment by dlpzx** [comment] 2023-11-08 08:30
Merged and released with v2.1.0 🚀

**Closed by dlpzx** 2023-11-08 08:30 UTC
Labels: type: newfeature, status: not-picked-yet
