### ISSUE TITLE
Share requests disappeared from UI after updated, we cannot revoke Shared Dataset.

### ISSUE THREAD

**Issue by anilprobable** [awslabs/aws-dataall#489] opened 2023-05-31 13:14 UTC
*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*
Hi,
I want to revoke shared dataset access from another account.

But for revoking, I can't see in the Received Request for that that dataset which I approved earlier from Share Request option, which I need to revoke and delete from there.

I cant see the all earlier received request too which approved earlier, after recent code change deployment done.

Please suggest, how can I revoke the access, for which I cant see the option in Received Request.

**Comment by dlpzx** [comment] 2023-05-31 13:39
Hi @anilprobable, thanks for the interest! Let me see if I understood your issue:
- Sharing for various datasets (DatasetA, DatasetB, DatasetC) was approved and granted (with you as part of the approver team)
- Now the sharing requests for DatasetA does not appear in your received share requests
- But the sharing requests for DatasetB and DatasetC appear in your received share requests

Is this your case?

**Comment by anilprobable** [comment] 2023-05-31 13:42
Yes.. thanks.. almost same scenario.

**Comment by dlpzx** [comment] 2023-06-02 08:17
I will try to recreate your issue, but it happens only in one Dataset right? Is there any particularity on this Dataset, any clue of what could be happening?

Also, for debugging, you can check the CloudWatch log-groups  and search the `share-manager` logs to see the reason why it failed. If you could provide some logs we will be able to help you find the issue

**Comment by anilprobable** [comment] 2023-06-02 09:18
Thanks for looking into it.
These old "received request" disappeared from share after deployment with updated cdk version to fix the nodejs 12 issue for lambda function. All old request got disappeared from dataall console.
Applied same in Dev and QA, but I cant see old request from QA only. From Dev I can see that old requests.

**Comment by dlpzx** [comment] 2023-06-06 14:58
Hi @anilprobable I was not able to recreate the issue, but maybe we can dig into your issue. 
- Are the share requests deleted from RDS? (let me know if you know how to get this info)
- Are the datasets still shared in LF?
- Do you have any logs of the particular day that the upgrade happenned?

**Comment by anilprobable** [comment] 2023-06-27 11:26
Sorry for delay in reply.

Could you please suggest , how can we deleted the shared DB manually from another account.

Here is details -
1. Account A - DB_name - xyz.
2. data.all created dataset for database xyz in data.all (Account A) - dataset_xyz
3. data.all shared this databases (xyz) for another AWS account - Account B and shared name is as example - xyz_shared_xxxxx
4. Due some to reason same database xyz from Account A, shared multiple times to Account B (all shared DB working fine while accessing the tables) and shared DB name is as follows -
xyz_shared_bbbbb
xyz_shared_ccccc
xyz_shared_ddddd

5. Now, I want to remove manually these extra shared DB from Account B.

Could you please let me know the manual steps from removing these additional Database from account B.
From data.all, we tried but still I can see few duplicate shared databases.


data.all ver - 1.4

**Comment by anilprobable** [comment] 2023-06-29 12:41
> Hi @dlpzx ,

Are the share requests deleted from RDS? (let me know if you know how to get this info) 
--> We didnt delete anything from RDS
Are the datasets still shared in LF?
--> Yes dataset still shared . (what LF represents here ? )
Do you have any logs of the particular day that the upgrade happened?
--> I dont have any logs for that in cloudwatch.

If you can please provide the steps for deleting the duplicate share which I asked in previously, would be appreciated.

**Comment by dlpzx** [comment] 2023-09-07 17:31
Hi @anilprobable, sorry for the late response. Are you still facing issues?
In your step 4, it is not a bug, it is the intended behavior if multiple share requests are opened:
xyz_shared_bbbbb --> for share request opened by team1
xyz_shared_ccccc --> by team 2
xyz_shared_ddddd --> by team 3

Is this your scenario? or do you have only one share request between account a and b?

When debugging I might have been a little cryptic. In general we need to check
1) what is the information in the metadata RDS database. You can connect to its query editor using the secret stored in secrets manager and querying the tables (such as the `share_object` table)
2) Lake formation = LF, I wanted to understand if the share request is successful under the hood
3)All API calls and ECS tasks in the central account have a dedicated CloudWatch log group. You can check what are the logs of the sharing task by going to the central account > cloudwatch > graohql log group or share-manager log group


Sorry again for the late response, let me know if you need any help

**Comment by anmolsgandhi** [comment] 2023-10-11 19:36
Since there has been no further communication, we are closing this issue. Please feel free to reopen the issue if you have any more questions or require further assistance.

**Closed by anmolsgandhi** 2023-10-11 19:36 UTC
Labels: status: can't reproduce, status: needs more info
