### ISSUE TITLE
Share request failing for Granular Share Request on v.2.0 

### ISSUE THREAD

**Issue by TejasRGitHub** [awslabs/aws-dataall#671] opened 2023-08-17 20:14 UTC
### Describe the bug

After creating a dataset with Granular Data sharing model , the share process is failing with below error - 

``Failed to share table dataall_granularshare_dataset_01_6948ss21 from source account <AWS Accunt>//us-east-1 with target account <AWS Accunt>//us-east-1due to: An error occurred (AccessDeniedException) when calling the GrantPermissions operation: Insufficient Glue permissions to access table dataall_granularshare_dataset_01_6948ss21``

### How to Reproduce

On the Producer Account -
1. Create a Dataset 
2. Upload a .csv file 
3. Start Crawler on the dataset and wait for the table to show up

On the consumer Account - 
1. Create a share request for the above dataset from the Catalog 
2. Go to the Shares Page, Add items in the share request and click submit

On Producer Account - 
1. Approve the request 

### Expected behavior

The share request items should show SHARE_SUCEEDED. With all the proper sharing of database and tables

### OS

Mac

### Python version

3.9

### AWS data.all version

2.0

**Comment by nikpodsh** [comment] 2023-08-18 06:51
Hello @TejasRGitHub ! Thanks for raising the issue! 
Most likely, it has the same root cause as #672. Let me check if I can reproduce the issue with the latest changes for modularization.

**Comment by noah-paige** [comment] 2023-08-22 22:49
We have seen this issue of `Insufficent Permissions on GrantPermissions Operation` in a similar issue here

https://github.com/awslabs/aws-dataall/issues/588


Looking at this comment
https://github.com/awslabs/aws-dataall/issues/588#issuecomment-1647328030

Typical scenarios when this happens:

    SCPs that block certain RAM actions
    Missing RAM permissions in the data.all pivotRole
    Glue Catalog Settings blocking sharing

**Comment by noah-paige** [comment] 2023-08-31 13:41
Thanks @TejasRGitHub for opening this issue

Closing as of now since the above PRs should resolve any issues seen with sharing in data.all v2.0 beta code...

Please re-open or create a new issue if additional problems persist

**Closed by noah-paige** 2023-08-31 13:41 UTC
Labels: status: can't reproduce, status: closing-soon, type: modularization
