### ISSUE TITLE
Does data.all support linking environments without DEFAULT vpcs?

### ISSUE THREAD

**Issue by zsaltys** [awslabs/aws-dataall#268] opened 2023-01-05 12:49 UTC
I have installed data.all on my AWS account. I then created a new environment and linked it to a separate account. When data.all runs the ECS task to deploy a CloudFormation stack it fails with this error:

[Error at /dataall-environment-ckn4tb5g] Could not find any VPCs matching {"account":"XXXXXX","region":"us-west-2","filter":{"isDefault":"true"},"returnAsymmetricSubnets":true,"lookupRoleArn":"arn:aws:iam::XXXXXXX:role/cdk-hnb659fds-lookup-role-XXXXXXX-us-west-2"}

I can see in the error message: "isDefault":"true". My XXXXXX account does not have a DEFAULT vpc as our org disables them by default and I cannot even create one. I have created a non default VPC in the XXXXXXX account but I don't see it picking it up.

**Comment by dlpzx** [comment] 2023-01-09 17:01
Hi @zsaltys, where do you get those logs? In CloudFormation?

From the code I can see that indeed we use the default VPC of the account as part of the environment CDK stack in `backend/dataall/cdkproxy/stacks/environment.py` line 553:

```
default_vpc = ec2.Vpc.from_lookup(self, 'VPCStudio', is_default=True)
vpc_id = default_vpc.vpc_id
```

But only if we want to use SageMaker ML Studio and we want to create a SageMaker domain. We can work on an enhancement of the feature to introduce pre-existing VPCs.

Regarding scheduling a meeting, let me check internally and get back to you. Thank you for the interest!

**Comment by zsaltys** [comment] 2023-01-16 11:35
@dlpzx I see these logs from the data.all UI when going to my specific environment, then STACK and then selecting LOGS.

![Uploading Screenshot 2023-01-16 at 11.34.40.png…]()

**Comment by zsaltys** [comment] 2023-01-16 11:36
@dlpzx are you saying if I disable "ML Studio (Requires Amazon Sagemaker Studio)" in my environment this issue should go away?

**Comment by zsaltys** [comment] 2023-01-16 11:46
@dlpzx can confirm that the issue went away once i disabled "ML Studio (Requires Amazon Sagemaker Studio)" in the environment. Could we convert this to a feature request to support non default VPCs?

**Comment by dlpzx** [comment] 2023-01-17 07:18
Hi @zsaltys thank you for testing it! Yes we can open an issue for this feature. How would you like it to work? Have VPCs as an optional parameter in the Environment creation? You can open the issue yourself as an enhancement or feature request and start working on it. Otherwise, I will create one this week to have visibility and we will discuss in the next iteration if it is picked up.

**Comment by dlpzx** [comment] 2023-01-23 08:17
Closing this question. The issue is addressed in https://github.com/awslabs/aws-dataall/issues/278

**Closed by dlpzx** 2023-01-23 08:17 UTC
Labels: question
